version: '2'
services:
  shield-mysql:
    #    image: mysql:8.0.16
    image: mysql:5.7.26
    #    volumes:
    #      - ~/volumes/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=6VDVpiRmeEcFx7Cazpf
      #  - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=shield
      - TZ=Asia/Shanghai
    ports:
      - 3307:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
